controller_manager_ns: 'robot_decapsuleur'
controller_list:
  - name: robot_decapsuleur_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_rot
      - joint_arm2
      - joint_arm4
