robot_decapsuleur:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - joint_rot
      - joint_arm2
      - joint_arm4
      - joint_arm6
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  arm_controller:
    type: joint_state_controller/JointStateController
    joints:
      - joint_rot
      - joint_arm1
      - joint_arm2
      - joint_arm3
      - joint_arm4
      - joint_arm5
      - joint_base_link
      - joint_base1
      - joint_base2
      - joint_arm6
      - joint_arm7
      - joint_lidar_support
      - joint_lidar
    gains:
      joint_rot:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_base_link:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_base1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_base2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_arm7:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_lidar_support:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_lidar:
        p: 100
        d: 1
        i: 1
        i_clamp: 1