joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_rot
    joint_speed: 1.5
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_arm2
    joint_speed: 1.5
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023

joint3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_arm4
    joint_speed: 1.5
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023

joint4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_arm6
    joint_speed: 1.5
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023
